export const GET_CLUSTER_INFO='GET_CLUSTER_INFO'
export const GET_MASTER_NODE_INFO='GET_MASTER_NODE_INFO'
export const GET_WORKER_NODE_INFO='GET_CLUSTER_NODE_INFO'
export const GET_PODS_INFO='GET_PODS_INFO'